### ISSUE TITLE
Icon and Banner for the app

### ISSUE THREAD

**Issue by vulpes-vulpeos** [FlagBrew/QRaken#2]
Hello. Couldn`t find QRaken thread on gbatemp so decided to open issue here.
I made banner and icon for QRaken. Banner font is from here: https://www.dafont.com/octopus.font
![qraken banner](https://user-images.githubusercontent.com/40931454/43587852-d66bec5a-9673-11e8-9aaa-7f5ab139e3c3.png)
<img width="24" alt="qraken icon 48" src="https://user-images.githubusercontent.com/40931454/43587853-d688c974-9673-11e8-8c43-4bf7a63e5490.png">
You can use it freely if you like it :D

**Comment by BernardoGiordano** [comment]
Thanks for the contribution but I'm not going to change them
